- src/OpenTracing/Ext/Tags.php
In https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table it is clearly stated that spans not only consist of RPC client and server relationships, but also  producer and consumer relationships when you are in a messaging context.
This PR adds those missing Tag constants as `SPAN_KIND_MESSAGE_BUS_PRODUCER` and `SPAN_KIND_MESSAGE_BUS_CONSUMER`.
> [EXT] `producer` and `consumer` span kinds

- src/OpenTracing/Span.php
`Span::finish` does not return anything. We should remove the annotation here.
Ping @felixfbecker @beberlei
> Removes an invalid return annotation

- src/OpenTracing/SpanReference.php
- tests/Unit/SpanReferenceTest.php
This PR follows from https://github.com/opentracing/opentracing-php/pull/12#issuecomment-320865558
Ping @felixfbecker @yurishkuro
> Removes per-type creation methods from SpanReference.

- src/OpenTracing/SpanContext.php
- src/OpenTracing/Tracer.php
There is a not clear strategy for when calling `SpanContext::getBaggageItem` and there is not value for such key. **Python API** returns `None` (see https://github.com/opentracing/opentracing-python/blob/master/opentracing/span.py#L190) so we could safely return a `null`.
Ping @yurishkuro @felixfbecker @beberlei
> Adds null as a valid return value when calling SpanContext::getBaggageItem

- src/OpenTracing/SpanOptions.php
- src/OpenTracing/Tracer.php
While working in the `OT` <> `Zipkin` bridge I found very inconvenient the fact that I should always need to pass a value for `$spanOptions` even if there is no values on it.
Another important concern here is the default start timestamp in the `SpanOptions`. As a vendor agnostic spec we can not set a default timestamp as of the unit depends on the vendor: ex. Zipkin uses microtime by default whereas datadog uses nanotime and other vendors could use a different one so I added documentation to the `startSpan` method.
Ping @yurishkuro @felixfbecker @beberlei
> Adds default value for spanOptions when creating a span.

- src/OpenTracing/Tracer.php
`register_shutdown_function` is the most common function for this case, message bus libraries are often using it so lets point out the main function.
> Replaces flush function hook in documentation.

- src/OpenTracing/NoopSpan.php
- src/OpenTracing/Span.php
Having setTags instead of setTag means that you would have to be aware of tags that are set in order to add aditional tag to a span. But that is not the case if we expose an interface to set just a single tag.
All other opentracing libraries also have setTag exposed instead of setTags so this helps to have more consistency between libraries.
Closes #51
> Introduce setTag method for a Span interface and get rid of setTags

- src/OpenTracing/NoopSpan.php
- src/OpenTracing/Span.php
Also see #53
This `$logRecords` is not documented by any PHP docs but I imply that implementation suppose to call `log()` before flushing.
Having that means
* `flush()` is responsible for two things
* this feature is specific to this library as it is not found in any other opentracing library
Instead promote usage of
```php
$span->log([...]);
$span->finish();
```
> Delete $logRecords argument from Span::finish()

- README.md
License information is added at the bottom of the README.md file along with the link.
> Add License Information

- README.md
- src/OpenTracing/Exceptions/InvalidSpanOption.php
- src/OpenTracing/Mock/MockScope.php
- src/OpenTracing/Mock/MockScopeManager.php
- src/OpenTracing/Mock/MockSpan.php
- src/OpenTracing/Mock/MockTracer.php
- src/OpenTracing/NoopScopeManager.php
- src/OpenTracing/NoopTracer.php
- src/OpenTracing/ScopeManager.php
- src/OpenTracing/StartSpanOptions.php
- src/OpenTracing/Tracer.php
- tests/OpenTracing/Mock/MockScopeManagerTest.php
- tests/OpenTracing/Mock/MockSpanTest.php
- tests/OpenTracing/Mock/MockTracerTest.php
- tests/OpenTracing/StartSpanOptionsTest.php
Read #61 for more context
- Changes the `Tracer::startActiveSpan` signature to return a scope.
- Changes the `ScopeManager` to not to be aware of spans
This is a breaking change but since we are still in beta, it is OK.
Fixes #61
Ping @beberlei @yurishkuro @ellisv @tedsuo
> [#60] Changes the API for the In process context propagation

- src/OpenTracing/Mock/MockScopeManager.php
- src/OpenTracing/NoopScopeManager.php
- src/OpenTracing/ScopeManager.php
- src/OpenTracing/StartSpanOptions.php
- Adds a default value for `$finishSpanOnClose` in `ScopeManager::activate`.
Closes #63
> [#63] Adds default value for finish_span_on_close in scope manager activation

- src/OpenTracing/Exceptions/InvalidSpanOption.php
- src/OpenTracing/StartSpanOptions.php
- src/OpenTracing/Tracer.php
- tests/OpenTracing/StartSpanOptionsTest.php
Both `Tracer::startSpan()` and `Tracer::startActiveSpan()` in implementation should start a new span as child of active span unless ignore_active_span option is set to true.
> Introduce ignore_active_span option

- src/OpenTracing/Tracer.php
Change a phpdoc by adjusting that `startActive()` also must use `ScopeManager::getActive()` span whenever ignore_active_span is false and child_of is not explicitly set.
Changed phpdoc is also validated against phpdoc.org generator.
> Update phpdoc for Tracer::startActiveSpan() and Tracer::startSpan()

- composer.json
💁‍♂️ For reference, see https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands:
>**Note**: Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are easily accessible. In this example no matter if the `phpunit` binary is actually in `vendor/bin/phpunit` or `bin/phpunit` it will be found and executed.
Follows https://github.com/opentracing/opentracing-php/pull/65#discussion_r202249213.
> Fix: Composer resolves binaries itself

- src/OpenTracing/NoopTracer.php
NoopTracer::startSpan was returning null instead of Span
> FIX Invalid return for NoopTracer::startSpan

- .travis.yml
As [PHP 7.4 is released](https://www.php.net/releases/7_4_0.php) since November 2019, we should add it to the Travis build matrix.
> chore: add PHP 7.4 to build matrix

- .travis.yml
- composer.json
- phpstan.neon
- src/OpenTracing/Mock/MockSpan.php
- src/OpenTracing/Reference.php
- src/OpenTracing/StartSpanOptions.php
- ensures interfaces are 7.1 compatible
- adds phpstan/phpstan to travis
- fixes 3 phpstan issues
Closes #94 
*Hint*:
I had to disable the `treatPhpDocTypesAsCertain` option for phpstan, otherwise it would complain about [an unreachable code block in Reference.php](https://github.com/opentracing/opentracing-php/blob/be33b2963dbe28ec365e33efe0b291e52ae47913/src/OpenTracing/Reference.php#L91).
> Upgrade interfaces from php56

- phpstan.neon
- src/OpenTracing/Mock/MockSpan.php
- src/OpenTracing/Mock/MockTracer.php
- tests/OpenTracing/Mock/MockTracerTest.php
- adds a test for `startSpan()` with references
- fixes the incompatibility mentioned in the issue
- increases the phpstan level (this would have caught the issue as well)
Closes #91
> fix MockSpan creation

- src/OpenTracing/Mock/MockTracer.php
- tests/OpenTracing/Mock/MockTracerTest.php
The `MockTracer` class provided by opentracing-php allows users to provide callables
implementing tracing context injection for a given format. The inject() method implementation,
when called with a given context, format and carrier, looks up the user-provided callable for the given format,
and invokes it via PHP's `call_user_func` function to perform the injection.
This implementation is broken, because `call_user_func` passes parameters to the target by value,
rather than by reference.[1] Since the injection process relies on the carrier being passed by reference,
so that the injection callable can modify the carrier, this will cause a PHP Warning and cause the injection to fail, e.g.:
> Parameter 2 to OpenTracing\Tests\Mock\MockTracerTest::OpenTracing\Tests\Mock\{closure}() expected to …
> Ensure carrier is passed by reference in MockTracer::inject

- src/OpenTracing/Mock/MockSpanContext.php
- src/OpenTracing/NoopSpanContext.php
- src/OpenTracing/SpanContext.php
As described in https://github.com/jcchavezs/zipkin-php-opentracing/pull/47/files/786ec41106b5905cfa7322fb54138c3289c1dce4#diff-97fcfff133419a8975edbc55468b44e719498b39a9a1f12b3f45ee7002d901e2
Note: This kind of errors are the ones which we should have avoided by test the implementation before doing the release.
> fix: fixes the return type for withBaggageItems.
